package com.ar.cac.homebanking.models.enums;

public enum Palabras {
    GATO, PERRO, OSO, LEÓN, TIGRE, ELEFANTE, JIRAFA, RINOCERONTE, TORTUGA, CANGURO,
    HORMIGA, MARIPOSA, CEBRA, COCODRILO, PINGÜINO, DELFÍN, RANA, MURCIÉLAGO, CIERVO,
    ESCORPIÓN, HURÓN, IGUANA, JAGUAR, KOALA, LÉMUR, NUTRIA, ORANGUTÁN, PANDA, QUOKKA,
    SURICATA, TARÁNTULA, OSO_PANDA, VACA, WOMBAT, YAK, ZORRO, ÑANDÚ, BÚFALO, AVISPÓN,
    BISONTE, CAMALEÓN, DINGO, EQUIDNA, FENNEC, GACELA, HIPÓTAMO, IMPALA, JACKAL
}
